### ISSUE TITLE
Release Tag Signing for Packaging

### ISSUE THREAD

**Issue by calesanz** [JJChiDguez/sibc#10]
Would it be possible to sign the tags of the releases?

I am currently packaging sibc for the arch user repository (`python-sibc-git`), because it is used in an other project.

Having signed tags/releases would allow users to have more confidence in the autenticity of the package.

Also it would be very helpful if you could create a new release with the MANIFEST.in from https://github.com/JJChiDguez/sibc/pull/9 .

Thanks

**Comment by JJChiDguez** [comment]
Hello there!
Thanks for the two above comments! I will handle them this week. 😉

**Comment by JJChiDguez** [comment]
I have done it! I will close this issue, but first, let me know if you are okay with it. I created the [release v1.0.3](https://github.com/JJChiDguez/sibc/releases/tag/v1.0.3).

**Comment by calesanz** [comment]
Thanks for the signing and new release this helps a lot.

The only issue now is that I do not have your public key yet. Would it be possible to upload it to a keyserver?

For example keyserver.ubuntu.com.

**Comment by JJChiDguez** [comment]
Done! I added to `keyserver.ubuntu.com`
I hope I correctly did it!

**Comment by calesanz** [comment]
Thanks it works!
