### ISSUE TITLE
How about Sigamal, C-Sigamal and Sims (simplification sigamal) on python

### ISSUE THREAD

**Issue by Dastgsm** [JJChiDguez/sibc#8]
Did you plan to make a code about Sigamal, C-Sigamal and Sims (simplification sigamal) on python; There is any code on magma about Sigamal but I don't have this software and can't experiment : http://tomoriya.work/code.html.

Chears,

**Comment by JJChiDguez** [comment]
Dear @Dastgsm,
Thanks for your interest in the Library.

Currently, We are focused on integrating `SIDH`, `SIKE`, `CSI-FiSh`, and `SeaSign`. But, SIDH and SIKE have priority.
Thus, `C-Sigamal` and `Sims` could be added later (but it will take time).

However, the main idea of the Library is to allow easy use for implementing other schemes.
And thus,  collaborate with other isogenist to then integrate/add new isogeny-based schemes.
So, I think you can use the `sibc` library and try implementing `C-Sigamal`.

Best regards
